---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html
    - /bin/mkdir -p "$DEPLOYPATH"
    - >
      /usr/bin/rsync -av --omit-dir-times --no-perms
      --exclude='.git/'
      --exclude='.github/'
      --exclude='node_modules/'
      --exclude='.env'
      --exclude='.env.*'
      --exclude='.cpanel.yml'
      ./ "$DEPLOYPATH/"
